import BaseModel from './BaseModel';

class Config extends BaseModel {
    /*
    "targetConsole": "X32",
    "designer": "Max Miller",
    "venue": "E-Free Church",
    "dcas": "1,2,3,4,5,6,7,8",
    "channels": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17",
    "backupChannels": "",
    "fxAssigns": "",
    "fxMutes": "",
    "defaultFX": "-1",
    "snippetRecall": "1",
    "fxBusMap": "1=13,2=14,3=15,4=16",
    "buttonMap": "0=12,1=11",
    "muteButtonMap": "1=5,0=6",
    "muteButtonAssignKeys": "",
    "profileSchemaVersion": "2",
    "qLabCues": "1",
    "consoleModel": "X32",
    "consoleVersion": "4.06-8",
    "consoleIP": "169.254.246.252",
    "consoleMAC": null,
    "autoConnect": "1",
    "enableChannelMonitoring": "1",
    "gangLR": "0",
    "gangLRChannels": "",
    "gangLRName": "Band",
    "gangLRColour": "11",
    "activeChannelHighlight": "1",
    "cueZeroSnippets": null,
    "minVersion": "3.0",
    "spareBackup": "20",
    "labelLR": "1",
    "labelTargetBus": "1000",
    "consoleMuteDCAUnassign": "1",
    "qLabPasscode": "1004",
    "suppressDCAMuteBackupSwitch": "0",
    "channelLevels": "1",
    "cueZeroResetLevels": "1",
    "sceneRecall": "0",
    "cueZeroScenes": "",
    "dimDCAFaders": "1",
    "qLabSuppressBack": "1",
    "qlclDyn1": "0",
    "cueZeroScenePoints": "",
    "dimDCAFadersSuppressColours": "1",
    "selectOnSpill": "1",
    "cueZeroActorLabels": "1",
    "dawRemote": "0",
    "dawIP": "127.0.0.1",
    "dawPreRoll": "0"
    */
}

export default Config;